### ISSUE TITLE
Feature Request: Shutdown Button

### ISSUE THREAD

**Issue by genestealer** [hjelev/rpi-mqtt-monitor#75]
A shutdown button that can shutdown the RPi on demand.
Simular to https://github.com/hjelev/rpi-mqtt-monitor/issues/29 but for shutdown.

**Comment by hjelev** [comment]
This is implemented now.

The button can be combined with wake-on-lan switch, unfortunately it can't be created with mqtt discovery message.

Here is how the wake-on-lan switch should look:
```
  - platform: wake_on_lan
    mac: "A8-A1-59-82-57-E7"
    host: "192.168.0.200"
    name: "ubuntu-pc-switch"
    turn_off:
      service: mqtt.publish
      data:
        topic: "homeassistant/update/ubuntu-pc/command"
        payload: "shutdown"
```
