### ISSUE TITLE
Change uptime to timestamp

### ISSUE THREAD

**Issue by genestealer** [hjelev/rpi-mqtt-monitor#76]
Can I suggest changing uptime, to a last boot timestamp. That way Home Assistant will automatically set the time formatting.
Like this:
![image](https://github.com/hjelev/rpi-mqtt-monitor/assets/5207490/f6eaa8f2-dd60-4c70-b473-fdfa1d59d6ed)
![image](https://github.com/hjelev/rpi-mqtt-monitor/assets/5207490/01ba0ad4-d0c5-49e7-ad68-ea4191a76e3b)

Mqtt auto discovery parameters : 

```YAML
{
  "name": "Last Boot",
  "state_topic": "xxxx",
  "device_class": "timestamp",
  "value_template": "{{ as_datetime(value) }}",
  "unique_id": "xxxx",
   etc,
   etc
  }
}
```
